# Generated by Django 4.2.30 on 2026-10-01 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '问答会话',
                'verbose_name_plural': '问答会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='引用来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='qa.questionsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '问答消息',
                'verbose_name_plural': '问答消息',
                'ordering': ['id'],
            },
        ),
    ]
