# Generated by Django 4.2.30 on 2026-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsession',
            name='summarized_message_count',
            field=models.PositiveIntegerField(default=0, help_text='按消息顺序，已并入 summary 的消息条数，避免重复摘要。', verbose_name='已摘要消息数'),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='被挤出滑动窗口的旧对话的滚动摘要，作为会话的长期记忆。', verbose_name='历史摘要'),
        ),
    ]
