# Generated by Django 4.2.30 on 2026-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('dept_admin', '部门管理员'), ('super_admin', '总管理员')], db_index=True, default='user', max_length=20, verbose_name='角色'),
        ),
    ]
