# Generated by Django 4.2.30 on 2026-10-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='部门管理员必须绑定部门，例如研发部、财务部', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', '普通员工'), ('dept_admin', '部门管理员'), ('super_admin', '总管理员')], db_index=True, default='user', max_length=20, verbose_name='角色'),
        ),
    ]
