# Generated by Django 4.2.30 on 2026-10-01 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('file', models.FileField(upload_to=documents.models.document_upload_to, verbose_name='文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(blank=True, max_length=16, verbose_name='文件类型')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('visibility', models.CharField(choices=[('public', '全员可见'), ('department', '部门可见')], default='department', max_length=16, verbose_name='可见范围')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('ready', '已就绪'), ('failed', '失败')], db_index=True, default='pending', max_length=16, verbose_name='处理状态')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='分块数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.department', verbose_name='所属部门')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='分块序号')),
                ('content', models.TextField(verbose_name='文本内容')),
                ('chroma_id', models.CharField(max_length=64, unique=True, verbose_name='Chroma ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='文档')),
            ],
            options={
                'verbose_name': '文档分块',
                'verbose_name_plural': '文档分块',
                'ordering': ['document_id', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
