# Generated by Django 4.2.30 on 2026-10-01 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='审批备注'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending_approval', '待审批'), ('rejected', '已驳回'), ('pending', '待处理'), ('processing', '处理中'), ('ready', '已就绪'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='处理状态'),
        ),
    ]
