# Generated by Django 4.2.30 on 2026-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', '登录'), ('logout', '退出'), ('register', '注册'), ('change_password', '修改密码'), ('upload_doc', '上传文档'), ('approve_doc', '审批通过'), ('reject_doc', '审批驳回'), ('delete_doc', '删除文档'), ('reprocess_doc', '重处理文档'), ('ask', '知识问答'), ('memory_reset', '重置会话记忆'), ('staff_update', '更新员工'), ('other', '其他')], db_index=True, max_length=32, verbose_name='动作'),
        ),
    ]
