"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

from decouple import Csv, config

# 项目根目录，也就是 manage.py 所在的 smart_kbqa/
BASE_DIR = Path(__file__).resolve().parent.parent

# 把 apps 目录加入模块搜索路径，这样 apps/ 下的应用可以直接用应用名导入。
sys.path.insert(0, str(BASE_DIR / 'apps'))


# ---------------------------------------------------------------------------
# 基础配置：全部从项目根目录的 .env 读取，字段模板见 .env.example
# ---------------------------------------------------------------------------

SECRET_KEY = config('DJANGO_SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())


# ---------------------------------------------------------------------------
# 应用与中间件
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_celery_beat',
    # 业务应用
    'accounts',
    'documents',
    'qa',
]

# 使用带部门字段的自定义用户模型
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware 必须排在 CommonMiddleware 之前，否则跨域响应头会丢失。
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ---------------------------------------------------------------------------
# 数据库：MySQL 8.0
# ---------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='smartkbqa'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# ---------------------------------------------------------------------------
# 密码校验
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# 国际化
# ---------------------------------------------------------------------------

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------------
# 静态文件与用户上传的文档
# ---------------------------------------------------------------------------

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# DRF + JWT
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=config('JWT_ACCESS_MINUTES', default=60, cast=int)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=config('JWT_REFRESH_DAYS', default=7, cast=int)
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ---------------------------------------------------------------------------
# 跨域
# ---------------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://127.0.0.1:3000,http://localhost:3000',
    cast=Csv(),
)


# ---------------------------------------------------------------------------
# Redis 与 Celery
# ---------------------------------------------------------------------------

REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
    }
}

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/1')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/2')
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# 本地未起 worker 时默认同步执行任务，避免文档一直停在 pending
CELERY_TASK_ALWAYS_EAGER = config(
    'CELERY_TASK_ALWAYS_EAGER',
    default=DEBUG,
    cast=bool,
)
CELERY_TASK_EAGER_PROPAGATES = True


# ---------------------------------------------------------------------------
# 向量库与模型服务
# ---------------------------------------------------------------------------

# http: 连接独立 Chroma 服务；persistent: 本地目录（当前默认，便于无 Docker 开发）
CHROMA_MODE = config('CHROMA_MODE', default='persistent')
CHROMA_HOST = config('CHROMA_HOST', default='127.0.0.1')
CHROMA_PORT = config('CHROMA_PORT', default=8001, cast=int)
CHROMA_PERSIST_DIR = BASE_DIR / config('CHROMA_PERSIST_DIR', default='data/chroma')
CHROMA_COLLECTION = config('CHROMA_COLLECTION', default='smart_kbqa')

DEEPSEEK_API_KEY = config('DEEPSEEK_API_KEY', default='')
DEEPSEEK_BASE_URL = config('DEEPSEEK_BASE_URL', default='https://api.deepseek.com')
LLM_MODEL = config('LLM_MODEL', default='deepseek-chat')

# embedding:
# - sentence: 本地中文语义模型（默认 BAAI/bge-small-zh-v1.5，推荐）
# - openai: OpenAI 兼容 embedding 接口
# - hash: 仅开发兜底，检索质量差
EMBEDDING_PROVIDER = config('EMBEDDING_PROVIDER', default='sentence')
EMBEDDING_MODEL = config(
    'EMBEDDING_MODEL',
    default='BAAI/bge-small-zh-v1.5',
)
EMBEDDING_API_KEY = config('EMBEDDING_API_KEY', default='')
EMBEDDING_BASE_URL = config('EMBEDDING_BASE_URL', default='')
EMBEDDING_DIM = config('EMBEDDING_DIM', default=384, cast=int)

CHUNK_SIZE = config('CHUNK_SIZE', default=800, cast=int)
CHUNK_OVERLAP = config('CHUNK_OVERLAP', default=120, cast=int)

FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
